# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Empowering African Voices in AI - Data, Models, and Innovation | DLI 2024 Workshop
email: chris.emezue@lanfrica.com
description: >- # this means to ignore newlines until "baseurl:"
  This DLI 2024 workshop is structured to explore both the human-centric and technical aspects of AI, particularly in under-resourced communities within the Global South. It will delve into critical considerations such as data generation, annotation, legal frameworks, and sharing protocols, emphasising culturally contextual datasets and the governance frameworks that support them. Furthermore, the workshop will address sharing AI models and datasets through various licensing frameworks, emphasizing ethical data collection, community engagement, and the management of AI innovations in a manner that respects local cultures and languages.
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://chrisemezue.github.io/empowering-african-voices.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ChrisEmezue
github_username:  chrisemezue

# Build settings
markdown: kramdown
remote_theme: bulma-clean-theme
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
